services:
  postgres:
    image: postgres:latest
    container_name: ecommerce-container
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvp-ecommerce

volumes:
  db-data:
